name: Resume Backend CD
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Build Function
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --rm-dist

      # Run AWS Terraform
      - name: Get Terraform Version
        id: tf_version
        run: echo "::set-output name=terraform-version::$(<deploy/.terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tf_version.outputs.terraform-version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: AWS Terraform Init
        id: aws_tf_init
        run: terraform init -input=false
        working-directory: deploy/aws

      - name: AWS Terraform Apply
        id: aws_tf_apply
        run: |
          terraform apply \
            -auto-approve \
            -var=function_base_path=../../dist/resume-backend_linux_amd64 \
            -input=false \
            -lock-timeout=300s
        working-directory: deploy/aws
