name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v2.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          context-name: PR Title